// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.kristen.rpc.darcher;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code darcher.Role}
   */
  public enum Role
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DOER = 0;</code>
     */
    DOER(0),
    /**
     * <code>TALKER = 1;</code>
     */
    TALKER(1),
    /**
     * <code>DAPP = 2;</code>
     */
    DAPP(2),
    /**
     * <code>DBMONITOR = 3;</code>
     */
    DBMONITOR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DOER = 0;</code>
     */
    public static final int DOER_VALUE = 0;
    /**
     * <code>TALKER = 1;</code>
     */
    public static final int TALKER_VALUE = 1;
    /**
     * <code>DAPP = 2;</code>
     */
    public static final int DAPP_VALUE = 2;
    /**
     * <code>DBMONITOR = 3;</code>
     */
    public static final int DBMONITOR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Role valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Role forNumber(int value) {
      switch (value) {
        case 0: return DOER;
        case 1: return TALKER;
        case 2: return DAPP;
        case 3: return DBMONITOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Role>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Role> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Role>() {
            public Role findValueByNumber(int number) {
              return Role.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final Role[] VALUES = values();

    public static Role valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Role(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:darcher.Role)
  }

  /**
   * Protobuf enum {@code darcher.Error}
   */
  public enum Error
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NilErr = 0;</code>
     */
    NilErr(0),
    /**
     * <code>InternalErr = 1;</code>
     */
    InternalErr(1),
    /**
     * <code>TimeoutErr = 2;</code>
     */
    TimeoutErr(2),
    /**
     * <code>ServiceNotAvailableErr = 3;</code>
     */
    ServiceNotAvailableErr(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NilErr = 0;</code>
     */
    public static final int NilErr_VALUE = 0;
    /**
     * <code>InternalErr = 1;</code>
     */
    public static final int InternalErr_VALUE = 1;
    /**
     * <code>TimeoutErr = 2;</code>
     */
    public static final int TimeoutErr_VALUE = 2;
    /**
     * <code>ServiceNotAvailableErr = 3;</code>
     */
    public static final int ServiceNotAvailableErr_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Error valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Error forNumber(int value) {
      switch (value) {
        case 0: return NilErr;
        case 1: return InternalErr;
        case 2: return TimeoutErr;
        case 3: return ServiceNotAvailableErr;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Error>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Error> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Error>() {
            public Error findValueByNumber(int number) {
              return Error.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Common.getDescriptor().getEnumTypes().get(1);
    }

    private static final Error[] VALUES = values();

    public static Error valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Error(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:darcher.Error)
  }

  /**
   * Protobuf enum {@code darcher.TxState}
   */
  public enum TxState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CREATED = 0;</code>
     */
    CREATED(0),
    /**
     * <code>PENDING = 1;</code>
     */
    PENDING(1),
    /**
     * <code>EXECUTED = 2;</code>
     */
    EXECUTED(2),
    /**
     * <code>DROPPED = 3;</code>
     */
    DROPPED(3),
    /**
     * <code>CONFIRMED = 4;</code>
     */
    CONFIRMED(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CREATED = 0;</code>
     */
    public static final int CREATED_VALUE = 0;
    /**
     * <code>PENDING = 1;</code>
     */
    public static final int PENDING_VALUE = 1;
    /**
     * <code>EXECUTED = 2;</code>
     */
    public static final int EXECUTED_VALUE = 2;
    /**
     * <code>DROPPED = 3;</code>
     */
    public static final int DROPPED_VALUE = 3;
    /**
     * <code>CONFIRMED = 4;</code>
     */
    public static final int CONFIRMED_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static TxState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TxState forNumber(int value) {
      switch (value) {
        case 0: return CREATED;
        case 1: return PENDING;
        case 2: return EXECUTED;
        case 3: return DROPPED;
        case 4: return CONFIRMED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TxState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TxState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TxState>() {
            public TxState findValueByNumber(int number) {
              return TxState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Common.getDescriptor().getEnumTypes().get(2);
    }

    private static final TxState[] VALUES = values();

    public static TxState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TxState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:darcher.TxState)
  }

  /**
   * <pre>
   **
   *TxError refers to errors that make transaction cannot be mined, or transaction is reverted due to internal errors in smart contract.
   * </pre>
   *
   * Protobuf enum {@code darcher.TxErrorType}
   */
  public enum TxErrorType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * nil type, should not be used.
     * </pre>
     *
     * <code>NIL_TxErr = 0;</code>
     */
    NIL_TxErr(0),
    /**
     * <pre>
     * internal error in smart contract occurs, transaction is reverted
     * </pre>
     *
     * <code>REVERT = 1;</code>
     */
    REVERT(1),
    /**
     * <pre>
     * bad transaction which cannot be mined and rejected by evm
     * </pre>
     *
     * <code>REJECT = 2;</code>
     */
    REJECT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * nil type, should not be used.
     * </pre>
     *
     * <code>NIL_TxErr = 0;</code>
     */
    public static final int NIL_TxErr_VALUE = 0;
    /**
     * <pre>
     * internal error in smart contract occurs, transaction is reverted
     * </pre>
     *
     * <code>REVERT = 1;</code>
     */
    public static final int REVERT_VALUE = 1;
    /**
     * <pre>
     * bad transaction which cannot be mined and rejected by evm
     * </pre>
     *
     * <code>REJECT = 2;</code>
     */
    public static final int REJECT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static TxErrorType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TxErrorType forNumber(int value) {
      switch (value) {
        case 0: return NIL_TxErr;
        case 1: return REVERT;
        case 2: return REJECT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TxErrorType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TxErrorType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TxErrorType>() {
            public TxErrorType findValueByNumber(int number) {
              return TxErrorType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Common.getDescriptor().getEnumTypes().get(3);
    }

    private static final TxErrorType[] VALUES = values();

    public static TxErrorType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TxErrorType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:darcher.TxErrorType)
  }

  public interface TxErrorMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:darcher.TxErrorMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hash = 1;</code>
     * @return The hash.
     */
    String getHash();
    /**
     * <code>string hash = 1;</code>
     * @return The bytes for hash.
     */
    com.google.protobuf.ByteString
        getHashBytes();

    /**
     * <code>.darcher.TxErrorType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.darcher.TxErrorType type = 2;</code>
     * @return The type.
     */
    TxErrorType getType();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code darcher.TxErrorMsg}
   */
  public static final class TxErrorMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:darcher.TxErrorMsg)
      TxErrorMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TxErrorMsg.newBuilder() to construct.
    private TxErrorMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxErrorMsg() {
      hash_ = "";
      type_ = 0;
      description_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TxErrorMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TxErrorMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              hash_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Common.internal_static_darcher_TxErrorMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Common.internal_static_darcher_TxErrorMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TxErrorMsg.class, Builder.class);
    }

    public static final int HASH_FIELD_NUMBER = 1;
    private volatile Object hash_;
    /**
     * <code>string hash = 1;</code>
     * @return The hash.
     */
    @Override
    public String getHash() {
      Object ref = hash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      }
    }
    /**
     * <code>string hash = 1;</code>
     * @return The bytes for hash.
     */
    @Override
    public com.google.protobuf.ByteString
        getHashBytes() {
      Object ref = hash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.darcher.TxErrorType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.darcher.TxErrorType type = 2;</code>
     * @return The type.
     */
    @Override public TxErrorType getType() {
      @SuppressWarnings("deprecation")
      TxErrorType result = TxErrorType.valueOf(type_);
      return result == null ? TxErrorType.UNRECOGNIZED : result;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile Object description_;
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @Override
    public String getDescription() {
      Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hash_);
      }
      if (type_ != TxErrorType.NIL_TxErr.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hash_);
      }
      if (type_ != TxErrorType.NIL_TxErr.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TxErrorMsg)) {
        return super.equals(obj);
      }
      TxErrorMsg other = (TxErrorMsg) obj;

      if (!getHash()
          .equals(other.getHash())) return false;
      if (type_ != other.type_) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TxErrorMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxErrorMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxErrorMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxErrorMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxErrorMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxErrorMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxErrorMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxErrorMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxErrorMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TxErrorMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxErrorMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxErrorMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TxErrorMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code darcher.TxErrorMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:darcher.TxErrorMsg)
        TxErrorMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Common.internal_static_darcher_TxErrorMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Common.internal_static_darcher_TxErrorMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TxErrorMsg.class, Builder.class);
      }

      // Construct using org.kristen.rpc.darcher.Common.TxErrorMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        hash_ = "";

        type_ = 0;

        description_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Common.internal_static_darcher_TxErrorMsg_descriptor;
      }

      @Override
      public TxErrorMsg getDefaultInstanceForType() {
        return TxErrorMsg.getDefaultInstance();
      }

      @Override
      public TxErrorMsg build() {
        TxErrorMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TxErrorMsg buildPartial() {
        TxErrorMsg result = new TxErrorMsg(this);
        result.hash_ = hash_;
        result.type_ = type_;
        result.description_ = description_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TxErrorMsg) {
          return mergeFrom((TxErrorMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TxErrorMsg other) {
        if (other == TxErrorMsg.getDefaultInstance()) return this;
        if (!other.getHash().isEmpty()) {
          hash_ = other.hash_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TxErrorMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TxErrorMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object hash_ = "";
      /**
       * <code>string hash = 1;</code>
       * @return The hash.
       */
      public String getHash() {
        Object ref = hash_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          hash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string hash = 1;</code>
       * @return The bytes for hash.
       */
      public com.google.protobuf.ByteString
          getHashBytes() {
        Object ref = hash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hash = 1;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      /**
       * <code>string hash = 1;</code>
       * @param value The bytes for hash to set.
       * @return This builder for chaining.
       */
      public Builder setHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hash_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.darcher.TxErrorType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.darcher.TxErrorType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.darcher.TxErrorType type = 2;</code>
       * @return The type.
       */
      @Override
      public TxErrorType getType() {
        @SuppressWarnings("deprecation")
        TxErrorType result = TxErrorType.valueOf(type_);
        return result == null ? TxErrorType.UNRECOGNIZED : result;
      }
      /**
       * <code>.darcher.TxErrorType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(TxErrorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.darcher.TxErrorType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public String getDescription() {
        Object ref = description_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:darcher.TxErrorMsg)
    }

    // @@protoc_insertion_point(class_scope:darcher.TxErrorMsg)
    private static final TxErrorMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TxErrorMsg();
    }

    public static TxErrorMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TxErrorMsg>
        PARSER = new com.google.protobuf.AbstractParser<TxErrorMsg>() {
      @Override
      public TxErrorMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxErrorMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxErrorMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TxErrorMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public TxErrorMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_darcher_TxErrorMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_darcher_TxErrorMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014common.proto\022\007darcher\"S\n\nTxErrorMsg\022\014\n" +
      "\004hash\030\001 \001(\t\022\"\n\004type\030\002 \001(\0162\024.darcher.TxEr" +
      "rorType\022\023\n\013description\030\003 \001(\t*5\n\004Role\022\010\n\004" +
      "DOER\020\000\022\n\n\006TALKER\020\001\022\010\n\004DAPP\020\002\022\r\n\tDBMONITO" +
      "R\020\003*P\n\005Error\022\n\n\006NilErr\020\000\022\017\n\013InternalErr\020" +
      "\001\022\016\n\nTimeoutErr\020\002\022\032\n\026ServiceNotAvailable" +
      "Err\020\003*M\n\007TxState\022\013\n\007CREATED\020\000\022\013\n\007PENDING" +
      "\020\001\022\014\n\010EXECUTED\020\002\022\013\n\007DROPPED\020\003\022\r\n\tCONFIRM" +
      "ED\020\004*4\n\013TxErrorType\022\r\n\tNIL_TxErr\020\000\022\n\n\006RE" +
      "VERT\020\001\022\n\n\006REJECT\020\002BQ\n\027org.kristen.rpc.da" +
      "rcherZ6github.com/Troublor/darcher-go-et" +
      "hereum/ethmonitor/rpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_darcher_TxErrorMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_darcher_TxErrorMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_darcher_TxErrorMsg_descriptor,
        new String[] { "Hash", "Type", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
